# Generated by Django 5.2.17 on 2026-08-19 17:03

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_email", models.EmailField(blank=True, max_length=254)),
                ("access_token", accounts.fields.EncryptedTextField()),
                ("refresh_token", accounts.fields.EncryptedTextField(blank=True)),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=255
                    ),
                ),
                ("client_id", accounts.fields.EncryptedTextField()),
                ("client_secret", accounts.fields.EncryptedTextField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
