# Generated by Django 5.2.17 on 2026-08-25 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_event_id", models.CharField(max_length=255)),
                ("calendar_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=1024)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=1024)),
                ("conference_url", models.URLField(blank=True, max_length=1024)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("attendees", models.JSONField(blank=True, default=list)),
                ("organizer_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
                "indexes": [
                    models.Index(
                        fields=["user", "start"], name="gcal_calend_user_id_8a27f5_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "google_event_id"), name="unique_event_per_user"
                    )
                ],
            },
        ),
    ]
