# Generated by Django 5.2.17 on 2026-08-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_task_id", models.CharField(max_length=255)),
                ("task_list_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=1024)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needsAction", "Needs action"),
                            ("completed", "Completed"),
                        ],
                        default="needsAction",
                        max_length=20,
                    ),
                ),
                ("due", models.DateTimeField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("google_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "google_task_id"), name="unique_task_per_user"
                    )
                ],
            },
        ),
    ]
